In [36]:
from data_import import *
from data_duplicates import *
from data_missing import *
from data_outliers import *
from data_encode import *
import pandas as pd

In [ ]:
file_path = 'path'  # replace by file path
df = pd.read_csv(file_path)

col = df.columns.values
df.columns = [x.strip() for x in col] # remove the stripping spaces

In [38]:
df_duplicates = scan_duplicates(df)
df_duplicates

['row 9999 is duplicated', 'row 10001 is duplicated']

In [39]:
df_temp = remove_duplicates(df)
df_temp.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [40]:
df_missing = scan_missing(df_temp)
df_missing

['row 4 column HasCrCard has missing value',
 'row 6 column Geography has missing value',
 'row 8 column IsActiveMember has missing value',
 'row 9 column Age has missing value']

In [41]:
df_temp = fill_missing_values_knn(df_temp)
df_temp.head(5)

Imputing row 1/10000 with 0 missing, elapsed time: 12.019
Imputing row 101/10000 with 0 missing, elapsed time: 12.019
Imputing row 201/10000 with 0 missing, elapsed time: 12.019
Imputing row 301/10000 with 0 missing, elapsed time: 12.019
Imputing row 401/10000 with 0 missing, elapsed time: 12.020
Imputing row 501/10000 with 0 missing, elapsed time: 12.020
Imputing row 601/10000 with 0 missing, elapsed time: 12.020
Imputing row 701/10000 with 0 missing, elapsed time: 12.020
Imputing row 801/10000 with 0 missing, elapsed time: 12.020
Imputing row 901/10000 with 0 missing, elapsed time: 12.020
Imputing row 1001/10000 with 0 missing, elapsed time: 12.021
Imputing row 1101/10000 with 0 missing, elapsed time: 12.021
Imputing row 1201/10000 with 0 missing, elapsed time: 12.021
Imputing row 1301/10000 with 0 missing, elapsed time: 12.021
Imputing row 1401/10000 with 0 missing, elapsed time: 12.021
Imputing row 1501/10000 with 0 missing, elapsed time: 12.021
Imputing row 1601/10000 with 0 missing, elapsed time: 12.021
Imputing row 1701/10000 with 0 missing, elapsed time: 12.022
Imputing row 1801/10000 with 0 missing, elapsed time: 12.022
Imputing row 1901/10000 with 0 missing, elapsed time: 12.022
Imputing row 2001/10000 with 0 missing, elapsed time: 12.022
Imputing row 2101/10000 with 0 missing, elapsed time: 12.022
Imputing row 2201/10000 with 0 missing, elapsed time: 12.022
Imputing row 2301/10000 with 0 missing, elapsed time: 12.023
Imputing row 2401/10000 with 0 missing, elapsed time: 12.023
Imputing row 2501/10000 with 0 missing, elapsed time: 12.023
Imputing row 2601/10000 with 0 missing, elapsed time: 12.023
Imputing row 2701/10000 with 0 missing, elapsed time: 12.023
Imputing row 2801/10000 with 0 missing, elapsed time: 12.023
Imputing row 2901/10000 with 0 missing, elapsed time: 12.023
Imputing row 3001/10000 with 0 missing, elapsed time: 12.024
Imputing row 3101/10000 with 0 missing, elapsed time: 12.024
Imputing row 3201/10000 with 0 missing, elapsed time: 12.024
Imputing row 3301/10000 with 0 missing, elapsed time: 12.024
Imputing row 3401/10000 with 0 missing, elapsed time: 12.024
Imputing row 3501/10000 with 0 missing, elapsed time: 12.024
Imputing row 3601/10000 with 0 missing, elapsed time: 12.025
Imputing row 3701/10000 with 0 missing, elapsed time: 12.025
Imputing row 3801/10000 with 0 missing, elapsed time: 12.025
Imputing row 3901/10000 with 0 missing, elapsed time: 12.025
Imputing row 4001/10000 with 0 missing, elapsed time: 12.025
Imputing row 4101/10000 with 0 missing, elapsed time: 12.025
Imputing row 4201/10000 with 0 missing, elapsed time: 12.025
Imputing row 4301/10000 with 0 missing, elapsed time: 12.026
Imputing row 4401/10000 with 0 missing, elapsed time: 12.026
Imputing row 4501/10000 with 0 missing, elapsed time: 12.026
Imputing row 4601/10000 with 0 missing, elapsed time: 12.026
Imputing row 4701/10000 with 0 missing, elapsed time: 12.026
Imputing row 4801/10000 with 0 missing, elapsed time: 12.026
Imputing row 4901/10000 with 0 missing, elapsed time: 12.026
Imputing row 5001/10000 with 0 missing, elapsed time: 12.026
Imputing row 5101/10000 with 0 missing, elapsed time: 12.026
Imputing row 5201/10000 with 0 missing, elapsed time: 12.028
Imputing row 5301/10000 with 0 missing, elapsed time: 12.028
Imputing row 5401/10000 with 0 missing, elapsed time: 12.028
Imputing row 5501/10000 with 0 missing, elapsed time: 12.028
Imputing row 5601/10000 with 0 missing, elapsed time: 12.028
Imputing row 5701/10000 with 0 missing, elapsed time: 12.028
Imputing row 5801/10000 with 0 missing, elapsed time: 12.029
Imputing row 5901/10000 with 0 missing, elapsed time: 12.029
Imputing row 6001/10000 with 0 missing, elapsed time: 12.029
Imputing row 6101/10000 with 0 missing, elapsed time: 12.029
Imputing row 6201/10000 with 0 missing, elapsed time: 12.029
Imputing row 6301/10000 with 0 missing, elapsed time: 12.029
Imputing row 6401/10000 with 0 missing, elapsed time: 12.029
Imputing row 6501/10000 with 0 missing, elapsed time: 12.029
Imputing row 6601/10000 with 0 missing, elapsed time: 12.029
Imputing row 6701/10000 with 0 missing, elapsed time: 12.029
Imputing row 6801/10000 with 0 missing, elapsed time: 12.030
Imputing row 6901/10000 with 0 missing, elapsed time: 12.030
Imputing row 7001/10000 with 0 missing, elapsed time: 12.030
Imputing row 7101/10000 with 0 missing, elapsed time: 12.030
Imputing row 7201/10000 with 0 missing, elapsed time: 12.030
Imputing row 7301/10000 with 0 missing, elapsed time: 12.031
Imputing row 7401/10000 with 0 missing, elapsed time: 12.031
Imputing row 7501/10000 with 0 missing, elapsed time: 12.031
Imputing row 7601/10000 with 0 missing, elapsed time: 12.031
Imputing row 7701/10000 with 0 missing, elapsed time: 12.031
Imputing row 7801/10000 with 0 missing, elapsed time: 12.031
Imputing row 7901/10000 with 0 missing, elapsed time: 12.032
Imputing row 8001/10000 with 0 missing, elapsed time: 12.032
Imputing row 8101/10000 with 0 missing, elapsed time: 12.032
Imputing row 8201/10000 with 0 missing, elapsed time: 12.032
Imputing row 8301/10000 with 0 missing, elapsed time: 12.032
Imputing row 8401/10000 with 0 missing, elapsed time: 12.032
Imputing row 8501/10000 with 0 missing, elapsed time: 12.032
Imputing row 8601/10000 with 0 missing, elapsed time: 12.033
Imputing row 8701/10000 with 0 missing, elapsed time: 12.033
Imputing row 8801/10000 with 0 missing, elapsed time: 12.033
Imputing row 8901/10000 with 0 missing, elapsed time: 12.033
Imputing row 9001/10000 with 0 missing, elapsed time: 12.033
Imputing row 9101/10000 with 0 missing, elapsed time: 12.033
Imputing row 9201/10000 with 0 missing, elapsed time: 12.033
Imputing row 9301/10000 with 0 missing, elapsed time: 12.034
Imputing row 9401/10000 with 0 missing, elapsed time: 12.034
Imputing row 9501/10000 with 0 missing, elapsed time: 12.034
Imputing row 9601/10000 with 0 missing, elapsed time: 12.034
Imputing row 9701/10000 with 0 missing, elapsed time: 12.034
Imputing row 9801/10000 with 0 missing, elapsed time: 12.034
Imputing row 9901/10000 with 0 missing, elapsed time: 12.034

d:\SEGP-G6\notebooks\data_missing.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_filled[column].fillna(most_frequent_value, inplace=True)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.000000,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.000000,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.000000,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.000000,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,0.554081,1.0,79084.10,0

In [42]:
df_outliers = scan_outliers(df_temp)
df_outliers

['Row 2 has outlier',
 'Row 7 has outlier',
 'Row 30 has outlier',
 'Row 35 has outlier',
 'Row 41 has outlier',
 'Row 43 has outlier',
 'Row 57 has outlier',
 'Row 58 has outlier',
 'Row 70 has outlier',
 'Row 85 has outlier',
 'Row 88 has outlier',
 'Row 90 has outlier',
 'Row 104 has outlier',
 'Row 114 has outlier',
 'Row 126 has outlier',
 'Row 127 has outlier',
 'Row 139 has outlier',
 'Row 149 has outlier',
 'Row 202 has outlier',
 'Row 223 has outlier',
 'Row 230 has outlier',
 'Row 238 has outlier',
 'Row 252 has outlier',
 'Row 271 has outlier',
 'Row 276 has outlier',
 'Row 297 has outlier',
 'Row 313 has outlier',
 'Row 361 has outlier',
 'Row 376 has outlier',
 'Row 379 has outlier',
 'Row 406 has outlier',
 'Row 413 has outlier',
 'Row 416 has outlier',
 'Row 458 has outlier',
 'Row 467 has outlier',
 'Row 494 has outlier',
 'Row 499 has outlier',
 'Row 516 has outlier',
 'Row 520 has outlier',
 'Row 538 has outlier',
 'Row 543 has outlier',
 'Row 544 has outlier',
 'Row 555 has outlier',
 'Row 559 has outlier',
 'Row 566 has outlier',
 'Row 584 has outlier',
 'Row 589 has outlier',
 'Row 598 has outlier',
 'Row 600 has outlier',
 'Row 602 has outlier',
 'Row 634 has outlier',
 'Row 656 has outlier',
 'Row 696 has outlier',
 'Row 705 has outlier',
 'Row 714 has outlier',
 'Row 720 has outlier',
 'Row 729 has outlier',
 'Row 734 has outlier',
 'Row 743 has outlier',
 'Row 764 has outlier',
 'Row 766 has outlier',
 'Row 767 has outlier',
 'Row 769 has outlier',
 'Row 805 has outlier',
 'Row 806 has outlier',
 'Row 813 has outlier',
 'Row 823 has outlier',
 'Row 838 has outlier',
 'Row 859 has outlier',
 'Row 881 has outlier',
 'Row 893 has outlier',
 'Row 904 has outlier',
 'Row 922 has outlier',
 'Row 933 has outlier',
 'Row 942 has outlier',
 'Row 952 has outlier',
 'Row 963 has outlier',
 'Row 995 has outlier',
 'Row 1005 has outlier',
 'Row 1086 has outlier',
 'Row 1096 has outlier',
 'Row 1110 has outlier',
 'Row 1111 has outlier',
 'Row 1114 has outlier',
 'Row 1117 has outlier',
 'Row 1122 has outlier',
 'Row 1158 has outlier',
 'Row 1171 has outlier',
 'Row 1193 has outlier',
 'Row 1210 has outlier',
 'Row 1254 has outlier',
 'Row 1265 has outlier',
 'Row 1281 has outlier',
 'Row 1305 has outlier',
 'Row 1328 has outlier',
 'Row 1341 has outlier',
 'Row 1351 has outlier',
 'Row 1376 has outlier',
 'Row 1381 has outlier',
 'Row 1388 has outlier',
 'Row 1410 has outlier',
 'Row 1427 has outlier',
 'Row 1438 has outlier',
 'Row 1443 has outlier',
 'Row 1457 has outlier',
 'Row 1469 has outlier',
 'Row 1485 has outlier',
 'Row 1492 has outlier',
 'Row 1626 has outlier',
 'Row 1631 has outlier',
 'Row 1676 has outlier',
 'Row 1701 has outlier',
 'Row 1746 has outlier',
 'Row 1755 has outlier',
 'Row 1798 has outlier',
 'Row 1807 has outlier',
 'Row 1810 has outlier',
 'Row 1811 has outlier',
 'Row 1827 has outlier',
 'Row 1838 has outlier',
 'Row 1845 has outlier',
 'Row 1847 has outlier',
 'Row 1876 has outlier',
 'Row 1916 has outlier',
 'Row 1922 has outlier',
 'Row 1955 has outlier',
 'Row 1962 has outlier',
 'Row 1977 has outlier',
 'Row 1981 has outlier',
 'Row 1987 has outlier',
 'Row 1993 has outlier',
 'Row 1996 has outlier',
 'Row 2007 has outlier',
 'Row 2050 has outlier',
 'Row 2053 has outlier',
 'Row 2092 has outlier',
 'Row 2094 has outlier',
 'Row 2110 has outlier',
 'Row 2124 has outlier',
 'Row 2152 has outlier',
 'Row 2154 has outlier',
 'Row 2195 has outlier',
 'Row 2196 has outlier',
 'Row 2245 has outlier',
 'Row 2274 has outlier',
 'Row 2285 has outlier',
 'Row 2340 has outlier',
 'Row 2431 has outlier',
 'Row 2458 has outlier',
 'Row 2459 has outlier',
 'Row 2462 has outlier',
 'Row 2495 has outlier',
 'Row 2499 has outlier',
 'Row 2509 has outlier',
 'Row 2536 has outlier',
 'Row 2541 has outlier',
 'Row 2542 has outlier',
 'Row 2546 has outlier',
 'Row 2553 has outlier',
 'Row 2574 has outlier',
 'Row 2600 has outlier',
 'Row 2614 has outlier',
 'Row 2617 has outlier',
 'Row 2619 has outlier',
 'Row 2658 has outlier',
 'Row 2670 has outlier',
 'Row 2689 has outlier',
 'Row 2720 has outlier',
 'Row 2750 has outlier',
 'Row 2775 has outlier',
 'Row 2853 has outlier',
 'Row 2872 has outlier',
 'Row 2900 has outlier',
 'Row 2939 has outlier',
 'Row 2945 has outlier',
 'Row 2962 has outlier',
 'Row 2967 has outlier',
 'Row 2970 has outlier',
 'Row 2977 has outlier',
 'Row 3032 has outlier',
 'Row 3109 has outlier',
 'Row 3142 has outlier',
 'Row 3152 has outlier',
 'Row 3166 has outlier',
 'Row 3170 has outlier',
 'Row 3171 has outlier',
 'Row 3204 has outlier',
 'Row 3250 has outlier',
 'Row 3251 has outlier',
 'Row 3280 has outlier',
 'Row 3294 has outlier',
 'Row 3300 has outlier',
 'Row 3317 has outlier',
 'Row 3367 has outlier',
 'Row 3473 has outlier',
 'Row 3490 has outlier',
 'Row 3497 has outlier',
 'Row 3530 has outlier',
 'Row 3531 has outlier',
 'Row 3549 has outlier',
 'Row 3600 has outlier',
 'Row 3615 has outlier',
 'Row 3637 has outlier',
 'Row 3645 has outlier',
 'Row 3659 has outlier',
 'Row 3715 has outlier',
 'Row 3724 has outlier',
 'Row 3731 has outlier',
 'Row 3836 has outlier',
 'Row 3841 has outlier',
 'Row 3843 has outlier',
 'Row 3888 has outlier',
 'Row 3983 has outlier',
 'Row 4013 has outlier',
 'Row 4014 has outlier',
 'Row 4026 has outlier',
 'Row 4037 has outlier',
 'Row 4062 has outlier',
 'Row 4064 has outlier',
 'Row 4166 has outlier',
 'Row 4175 has outlier',
 'Row 4206 has outlier',
 'Row 4211 has outlier',
 'Row 4215 has outlier',
 'Row 4241 has outlier',
 'Row 4260 has outlier',
 'Row 4274 has outlier',
 'Row 4280 has outlier',
 'Row 4295 has outlier',
 'Row 4297 has outlier',
 'Row 4318 has outlier',
 'Row 4335 has outlier',
 'Row 4367 has outlier',
 'Row 4373 has outlier',
 'Row 4463 has outlier',
 'Row 4471 has outlier',
 'Row 4511 has outlier',
 'Row 4516 has outlier',
 'Row 4520 has outlier',
 'Row 4533 has outlier',
 'Row 4547 has outlier',
 'Row 4549 has outlier',
 'Row 4563 has outlier',
 'Row 4579 has outlier',
 'Row 4606 has outlier',
 'Row 4608 has outlier',
 'Row 4619 has outlier',
 'Row 4643 has outlier',
 'Row 4653 has outlier',
 'Row 4654 has outlier',
 'Row 4677 has outlier',
 'Row 4748 has outlier',
 'Row 4781 has outlier',
 'Row 4822 has outlier',
 'Row 4842 has outlier',
 'Row 4901 has outlier',
 'Row 4912 has outlier',
 'Row 4967 has outlier',
 'Row 4992 has outlier',
 'Row 5007 has outlier',
 'Row 5020 has outlier',
 'Row 5082 has outlier',
 'Row 5093 has outlier',
 'Row 5114 has outlier',
 'Row 5137 has outlier',
 'Row 5235 has outlier',
 'Row 5264 has outlier',
 'Row 5285 has outlier',
 'Row 5314 has outlier',
 'Row 5337 has outlier',
 'Row 5386 has outlier',
 'Row 5390 has outlier',
 'Row 5596 has outlier',
 'Row 5640 has outlier',
 'Row 5700 has outlier',
 'Row 5742 has outlier',
 'Row 5750 has outlier',
 'Row 5791 has outlier',
 'Row 5798 has outlier',
 'Row 5817 has outlier',
 'Row 5881 has outlier',
 'Row 5882 has outlier',
 'Row 5888 has outlier',
 'Row 5950 has outlier',
 'Row 5962 has outlier',
 'Row 5976 has outlier',
 'Row 6000 has outlier',
 'Row 6023 has outlier',
 'Row 6046 has outlier',
 'Row 6054 has outlier',
 'Row 6081 has outlier',
 'Row 6116 has outlier',
 'Row 6131 has outlier',
 'Row 6165 has outlier',
 'Row 6184 has outlier',
 'Row 6221 has outlier',
 'Row 6226 has outlier',
 'Row 6262 has outlier',
 'Row 6273 has outlier',
 'Row 6279 has outlier',
 'Row 6295 has outlier',
 'Row 6314 has outlier',
 'Row 6324 has outlier',
 'Row 6346 has outlier',
 'Row 6354 has outlier',
 'Row 6399 has outlier',
 'Row 6440 has outlier',
 'Row 6508 has outlier',
 'Row 6515 has outlier',
 'Row 6524 has outlier',
 'Row 6530 has outlier',
 'Row 6556 has outlier',
 'Row 6567 has outlier',
 'Row 6581 has outlier',
 'Row 6669 has outlier',
 'Row 6684 has outlier',
 'Row 6709 has outlier',
 'Row 6713 has outlier',
 'Row 6715 has outlier',
 'Row 6717 has outlier',
 'Row 6721 has outlier',
 'Row 6734 has outlier',
 'Row 6750 has outlier',
 'Row 6782 has outlier',
 'Row 6831 has outlier',
 'Row 6869 has outlier',
 'Row 6875 has outlier',
 'Row 6878 has outlier',
 'Row 6890 has outlier',
 'Row 6912 has outlier',
 'Row 6928 has outlier',
 'Row 6964 has outlier',
 'Row 7031 has outlier',
 'Row 7053 has outlier',
 'Row 7058 has outlier',
 'Row 7103 has outlier',
 'Row 7136 has outlier',
 'Row 7138 has outlier',
 'Row 7139 has outlier',
 'Row 7144 has outlier',
 'Row 7165 has outlier',
 'Row 7181 has outlier',
 'Row 7213 has outlier',
 'Row 7242 has outlier',
 'Row 7248 has outlier',
 'Row 7253 has outlier',
 'Row 7257 has outlier',
 'Row 7258 has outlier',
 'Row 7266 has outlier',
 'Row 7316 has outlier',
 'Row 7324 has outlier',
 'Row 7328 has outlier',
 'Row 7338 has outlier',
 'Row 7339 has outlier',
 'Row 7341 has outlier',
 'Row 7353 has outlier',
 'Row 7358 has outlier',
 'Row 7453 has outlier',
 'Row 7455 has outlier',
 'Row 7477 has outlier',
 'Row 7492 has outlier',
 'Row 7523 has outlier',
 'Row 7533 has outlier',
 'Row 7567 has outlier',
 'Row 7570 has outlier',
 'Row 7590 has outlier',
 'Row 7629 has outlier',
 'Row 7658 has outlier',
 'Row 7698 has outlier',
 'Row 7715 has outlier',
 'Row 7718 has outlier',
 'Row 7722 has outlier',
 'Row 7724 has outlier',
 'Row 7729 has outlier',
 'Row 7733 has outlier',
 'Row 7741 has outlier',
 'Row 7759 has outlier',
 'Row 7773 has outlier',
 'Row 7777 has outlier',
 'Row 7834 has outlier',
 'Row 7882 has outlier',
 'Row 7909 has outlier',
 'Row 7915 has outlier',
 'Row 7994 has outlier',
 'Row 7995 has outlier',
 'Row 7998 has outlier',
 'Row 8010 has outlier',
 'Row 8041 has outlier',
 'Row 8049 has outlier',
 'Row 8075 has outlier',
 'Row 8076 has outlier',
 'Row 8098 has outlier',
 'Row 8103 has outlier',
 'Row 8170 has outlier',
 'Row 8171 has outlier',
 'Row 8217 has outlier',
 'Row 8242 has outlier',
 'Row 8299 has outlier',
 'Row 8305 has outlier',
 'Row 8336 has outlier',
 'Row 8344 has outlier',
 'Row 8347 has outlier',
 'Row 8359 has outlier',
 'Row 8374 has outlier',
 'Row 8379 has outlier',
 'Row 8390 has outlier',
 'Row 8401 has outlier',
 'Row 8427 has outlier',
 'Row 8432 has outlier',
 'Row 8452 has outlier',
 'Row 8460 has outlier',
 'Row 8471 has outlier',
 'Row 8478 has outlier',
 'Row 8493 has outlier',
 'Row 8531 has outlier',
 'Row 8562 has outlier',
 'Row 8568 has outlier',
 'Row 8577 has outlier',
 'Row 8590 has outlier',
 'Row 8683 has outlier',
 'Row 8706 has outlier',
 'Row 8723 has outlier',
 'Row 8761 has outlier',
 'Row 8762 has outlier',
 'Row 8763 has outlier',
 'Row 8787 has outlier',
 'Row 8794 has outlier',
 'Row 8807 has outlier',
 'Row 8826 has outlier',
 'Row 8850 has outlier',
 'Row 8862 has outlier',
 'Row 8884 has outlier',
 'Row 8887 has outlier',
 'Row 8923 has outlier',
 'Row 8931 has outlier',
 'Row 8935 has outlier',
 'Row 8953 has outlier',
 'Row 8963 has outlier',
 'Row 9008 has outlier',
 'Row 9010 has outlier',
 'Row 9034 has outlier',
 'Row 9060 has outlier',
 'Row 9102 has outlier',
 'Row 9106 has outlier',
 'Row 9125 has outlier',
 'Row 9138 has outlier',
 'Row 9140 has outlier',
 'Row 9153 has outlier',
 'Row 9171 has outlier',
 'Row 9186 has outlier',
 'Row 9206 has outlier',
 'Row 9210 has outlier',
 'Row 9215 has outlier',
 'Row 9232 has outlier',
 'Row 9255 has outlier',
 'Row 9276 has outlier',
 'Row 9292 has outlier',
 'Row 9316 has outlier',
 'Row 9318 has outlier',
 'Row 9323 has outlier',
 'Row 9326 has outlier',
 'Row 9337 has outlier',
 'Row 9357 has outlier',
 'Row 9370 has outlier',
 'Row 9380 has outlier',
 'Row 9384 has outlier',
 'Row 9411 has outlier',
 'Row 9426 has outlier',
 'Row 9438 has outlier',
 'Row 9440 has outlier',
 'Row 9447 has outlier',
 'Row 9472 has outlier',
 'Row 9513 has outlier',
 'Row 9554 has outlier',
 'Row 9555 has outlier',
 'Row 9565 has outlier',
 'Row 9572 has outlier',
 'Row 9600 has outlier',
 'Row 9610 has outlier',
 'Row 9613 has outlier',
 'Row 9624 has outlier',
 'Row 9625 has outlier',
 'Row 9638 has outlier',
 'Row 9646 has outlier',
 'Row 9677 has outlier',
 'Row 9690 has outlier',
 'Row 9693 has outlier',
 'Row 9727 has outlier',
 'Row 9747 has outlier',
 'Row 9768 has outlier',
 'Row 9831 has outlier',
 'Row 9834 has outlier',
 'Row 9877 has outlier',
 'Row 9879 has outlier',
 'Row 9884 has outlier',
 'Row 9895 has outlier',
 'Row 9920 has outlier',
 'Row 9936 has outlier',
 'Row 9962 has outlier',
 'Row 9997 has outlier']

In [43]:
df_temp = remove_outliers(df_temp)
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9500 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9500 non-null   int64
 1   CustomerId       9500 non-null   int64
 2   Surname          9500 non-null   object
 3   CreditScore      9500 non-null   int64
 4   Geography        9500 non-null   object
 5   Gender           9500 non-null   object
 6   Age              9500 non-null   float64
 7   Tenure           9500 non-null   int64
 8   Balance          9500 non-null   float64
 9   NumOfProducts    9500 non-null   int64
 10  HasCrCard        9500 non-null   float64
 11  IsActiveMember   9500 non-null   float64
 12  EstimatedSalary  9500 non-null   float64
 13  Exited           9500 non-null   int64
dtypes: float64(5), int64(6), object(3)
memory usage: 1.1+ MB

In [44]:
df_result = encode_categorical_features(df_temp)

Column 'Surname' has 2856 unique values, keeping original.