In [10]:
from data_import import *
from data_display import *
from data_duplicates import *
from data_outliers import *
from data_missing import *
from data_encode import *
from data_remove import *

In [11]:
file_path = 'Churn_Modelling.csv'  # replace by file path
df = load_data(file_path)

col = df.columns.values
df.columns = [x.strip() for x in col] # remove the stripping spaces

In [12]:
choice = "head"
num_rows = 1
display_data(df, choice, num_rows)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.0,1,1.0,1.0,101348.88,1

In [13]:
df_duplicates = find_duplicates(df)
df_duplicates

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [ ]:
df_new = remove_rows(df, 9998)
display_data(df_new, "tail", 10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9990,9991,15798964,Nkemakonam,714,Germany,Male,33.0,3,35016.60,1,1.0,0.0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53.0,4,88381.21,1,1.0,0.0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36.0,2,0.00,1,1.0,0.0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28.0,7,155060.41,1,1.0,0.0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29.0,2,0.00,2,0.0,0.0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1.0,0.0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1.0,1.0,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0.0,1.0,42085.58,1
9999,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10001,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [18]:
outliers_dict = {}

for column in df.select_dtypes(include=np.number).columns:
    df_outliers = find_outliers_percentile(df, column)
            
    # Only add columns with outliers to the dictionary
    if not df_outliers.empty:
        outliers_dict[column] = df_outliers

outliers_dict["Age"]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
57,58,15647091,Endrizzi,725,Germany,Male,19.0,0,75888.20,1,0.0,0.0,45613.75,0
85,86,15805254,Ndukaku,652,Spain,Female,75.0,10,0.00,2,1.0,1.0,114675.75,0
158,159,15589975,Maclean,646,France,Female,73.0,6,97259.25,1,0.0,1.0,104719.66,0
233,234,15723886,Fiore,767,Germany,Male,20.0,3,119714.25,2,0.0,1.0,150135.38,0
252,253,15793726,Matveyeva,681,France,Female,79.0,0,0.00,2,0.0,1.0,170968.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9782,9783,15728829,Weigel,509,France,Male,18.0,7,102983.91,1,1.0,0.0,171770.58,0
9894,9895,15704795,Vagin,521,France,Female,77.0,6,0.00,2,1.0,1.0,49054.10,0
9932,9933,15813451,Fleetwood-Smith,677,Spain,Male,18.0,8,134796.87,2,1.0,1.0,114858.90,0
9936,9937,15653037,Parks,609,France,Male,77.0,1,0.00,1,0.0,1.0,18708.76,0
9940,9941,15791972,Bergamaschi,748,France,Female,20.0,7,0.00,2,0.0,0.0,10792.42,0

In [8]:

df_no_outliers, df_outliers = remove_outliers(df_no_duplicates, 'column_name') #need to get changed, outliers may be needed for other purposes
df_no_empty = fill_missing_with(df_no_outliers, 'column_name') #for different columns we need different functions
df_encoded  = encode_categorical_features(df_no_empty)

NameError: name 'remove_outliers' is not defined